export interface MacroCategory {
  slug: string;
  name: string;
  icon: string;
}

// ~16 categorías madre que agrupan las ~180 categorías crudas
// que vienen del breadcrumb de Mercado Libre.
export const macroCategories: MacroCategory[] = [
  { slug: 'tecnologia', name: 'Tecnología', icon: '💻' },
  { slug: 'audio-video', name: 'Audio, TV y Video', icon: '🎬' },
  { slug: 'hogar', name: 'Hogar', icon: '🏠' },
  { slug: 'electrodomesticos', name: 'Electrodomésticos', icon: '🍳' },
  { slug: 'herramientas', name: 'Herramientas y Construcción', icon: '🛠️' },
  { slug: 'jardin-aire-libre', name: 'Jardín y Aire Libre', icon: '🌱' },
  { slug: 'deportes-fitness', name: 'Deportes y Fitness', icon: '⚽' },
  { slug: 'belleza', name: 'Belleza y Cuidado Personal', icon: '✨' },
  { slug: 'salud', name: 'Salud y Bienestar', icon: '⚕️' },
  { slug: 'bebes-ninos', name: 'Bebés y Niños', icon: '🧸' },
  { slug: 'mascotas', name: 'Mascotas', icon: '🐾' },
  { slug: 'autos-motos', name: 'Autos y Motos', icon: '🚗' },
  { slug: 'moda', name: 'Moda y Accesorios', icon: '👗' },
  { slug: 'oficina-comercio', name: 'Oficina y Comercio', icon: '🏢' },
  { slug: 'musica', name: 'Instrumentos Musicales', icon: '🎵' },
  { slug: 'otros', name: 'Otros', icon: '📦' },
];

// Mapeo exacto: nombre de categoría cruda (breadcrumb de ML) -> slug de categoría madre.
const RAW_TO_MACRO: Record<string, string> = {
  'Aberturas': 'herramientas',
  'Abrigos': 'moda',
  'Acc. Para Motos Y Cuatriciclos': 'autos-motos',
  'Accesorios De Auto Y Camioneta': 'autos-motos',
  'Accesorios De Construcción': 'herramientas',
  'Accesorios De Moda': 'moda',
  'Accesorios Para Audio Y Video': 'audio-video',
  'Accesorios Para Celulares': 'tecnologia',
  'Accesorios Para Consolas': 'audio-video',
  'Accesorios Para Cámaras': 'tecnologia',
  'Accesorios Para Herramientas': 'herramientas',
  'Accesorios Para Línea Pesada': 'autos-motos',
  'Accesorios Para Pc Gaming': 'tecnologia',
  'Accesorios Para Tv': 'audio-video',
  'Adornos Y Decoración Del Hogar': 'hogar',
  'Almacenamiento': 'oficina-comercio',
  'Andadores Y Vehículos De Bebés': 'bebes-ninos',
  'Antigüedades': 'oficina-comercio',
  'Arquitectura Y Diseño': 'oficina-comercio',
  'Arte Y Manualidades': 'oficina-comercio',
  'Artefactos Para El Cabello': 'belleza',
  'Artes Marciales Y Boxeo': 'deportes-fitness',
  'Artículos De Bebés Para Baño': 'bebes-ninos',
  'Artículos De Maternidad': 'bebes-ninos',
  'Artículos De Peluquería': 'belleza',
  'Audio': 'audio-video',
  'Audio Para Vehículos': 'autos-motos',
  'Aves': 'mascotas',
  'Banderas': 'oficina-comercio',
  'Barbería': 'belleza',
  'Baterías Y Percusión': 'musica',
  'Bazar Y Cocina': 'hogar',
  'Baños': 'hogar',
  'Baños Y Sanitarios': 'hogar',
  'Cajas Y Organizadores': 'hogar',
  'Calzado': 'moda',
  'Calzas': 'moda',
  'Camas, Colchones Y Accesorios': 'hogar',
  'Camisas': 'moda',
  'Camping, Caza Y Pesca': 'jardin-aire-libre',
  'Celulares Y Smartphones': 'tecnologia',
  'Ciclismo': 'deportes-fitness',
  'Climatización': 'electrodomesticos',
  'Cocción': 'electrodomesticos',
  'Componentes De Pc': 'tecnologia',
  'Conectividad Y Redes': 'tecnologia',
  'Consolas': 'audio-video',
  'Controles Remotos': 'tecnologia',
  'Corralitos': 'bebes-ninos',
  'Cotillón': 'oficina-comercio',
  'Cuidado De La Piel': 'belleza',
  'Cuidado De La Salud': 'salud',
  'Cuidado Del Cabello': 'belleza',
  'Cuidado Del Hogar Y Lavandería': 'hogar',
  'Cámaras': 'tecnologia',
  'Decoración Para Fiestas': 'oficina-comercio',
  'Depilación': 'belleza',
  'Descartables Para Fiestas': 'oficina-comercio',
  'Disfraces Y Cosplay': 'bebes-ninos',
  'Dispensadores Y Purificadores': 'hogar',
  'Drones Y Accesorios': 'tecnologia',
  'Electricidad': 'herramientas',
  'Embalaje Y Logística': 'oficina-comercio',
  'Energia Renovable': 'herramientas',
  'Equipaje, Bolsos Y Carteras': 'moda',
  'Equipamiento Médico': 'salud',
  'Equipamiento Para Comercios': 'oficina-comercio',
  'Equipamiento Para Oficinas': 'oficina-comercio',
  'Esqui Y Snowboard': 'deportes-fitness',
  'Estabilizadores Y Ups': 'tecnologia',
  'Figuritas, Álbumes Y Cromos': 'bebes-ninos',
  'Fitness Y Musculación': 'deportes-fitness',
  'Fútbol': 'deportes-fitness',
  'Gastronomía Y Hotelería': 'oficina-comercio',
  'Gatos': 'mascotas',
  'Golf': 'deportes-fitness',
  'Gráfica E Impresión': 'oficina-comercio',
  'Handies Y Radiofrecuencia': 'tecnologia',
  'Herramientas De Trabajo': 'herramientas',
  'Herramientas Eléctricas': 'herramientas',
  'Herramientas Industriales': 'herramientas',
  'Herramientas Manuales': 'herramientas',
  'Herramientas Neumáticas': 'herramientas',
  'Herramientas Para Jardín': 'jardin-aire-libre',
  'Herramientas Para Vehículos': 'autos-motos',
  'Higiene Personal': 'belleza',
  'Higiene Y Cuidado Del Bebé': 'bebes-ninos',
  'Hobbies': 'oficina-comercio',
  'Iluminación Para El Hogar': 'hogar',
  'Impresión': 'tecnologia',
  'Indumentaria Laboral Y Escolar': 'moda',
  'Infraestructura Rural': 'herramientas',
  'Instrumentos De Cuerdas': 'musica',
  'Instrumentos De Viento': 'musica',
  'Instrumentos Ópticos': 'herramientas',
  'Insumos Agrícolas': 'herramientas',
  'Insumos Para Joyería': 'oficina-comercio',
  'Jardin Y Aire Libre': 'jardin-aire-libre',
  'Juegos De Mesa Y Cartas': 'bebes-ninos',
  'Juegos De Plaza Y Aire Libre': 'bebes-ninos',
  'Juegos Y Juguetes Para Bebés': 'bebes-ninos',
  'Juguetes De Construcción': 'bebes-ninos',
  'Lactancia Y Alimentación': 'bebes-ninos',
  'Lavado': 'hogar',
  'Lectores Y Scanners': 'tecnologia',
  'Librería': 'oficina-comercio',
  'Limpieza De Vehículos': 'autos-motos',
  'Lubricantes Y Fluidos': 'autos-motos',
  'Manicura Y Pedicura': 'belleza',
  'Maquillaje': 'belleza',
  'Maquinarias Para Construcción': 'herramientas',
  'Masajes': 'belleza',
  'Materiales De Obra': 'herramientas',
  'Media Streaming': 'audio-video',
  'Mercería': 'oficina-comercio',
  'Monitores Y Accesorios': 'tecnologia',
  'Monopatines Y Scooters': 'deportes-fitness',
  'Montañismo Y Trekking': 'deportes-fitness',
  'Movilidad': 'salud',
  'Muebles Para El Hogar': 'hogar',
  'Muñecos Y Muñecas': 'bebes-ninos',
  'Música': 'musica',
  'Navegadores Gps Para Vehículos': 'autos-motos',
  'Neumáticos': 'autos-motos',
  'Notebooks Y Accesorios': 'tecnologia',
  'Organización Para El Hogar': 'hogar',
  'Ortopedia': 'salud',
  'Otros': 'otros',
  'Pantalones': 'moda',
  'Paseo Del Bebé': 'bebes-ninos',
  'Pc De Escritorio': 'tecnologia',
  'Pedales Y Accesorios': 'musica',
  'Pequeños Electrodomésticos': 'electrodomesticos',
  'Perfumes': 'belleza',
  'Periféricos De Pc': 'tecnologia',
  'Perros': 'mascotas',
  'Pilas Y Cargadores': 'tecnologia',
  'Pinturería': 'herramientas',
  'Pisos Y Revestimientos': 'herramientas',
  'Plomería': 'herramientas',
  'Producción Animal': 'mascotas',
  'Proyectores Y Pantallas': 'audio-video',
  'Publicidad Y Promoción': 'oficina-comercio',
  'Pulsómetros Y Cronómetros': 'deportes-fitness',
  'Refrigeración': 'electrodomesticos',
  'Relojes': 'moda',
  'Remeras, Musculosas Y Chombas': 'moda',
  'Repuestos Autos Y Camionetas': 'autos-motos',
  'Repuestos Motos Y Cuatriciclos': 'autos-motos',
  'Repuestos Náuticos': 'autos-motos',
  'Repuestos Para Tv': 'audio-video',
  'Ropa Deportiva': 'deportes-fitness',
  'Ropa Interior Y De Dormir': 'moda',
  'Salud Del Bebé': 'bebes-ninos',
  'Seguridad Laboral': 'herramientas',
  'Seguridad Para Bebés': 'bebes-ninos',
  'Seguridad Para El Hogar': 'hogar',
  'Seguridad Vehicular': 'autos-motos',
  'Sin Categoría': 'otros',
  'Smartwatches Y Accesorios': 'tecnologia',
  'Souvenirs Para Fiestas': 'oficina-comercio',
  'Suplementos Alimenticios': 'deportes-fitness',
  'Suplementos Y Shakers': 'deportes-fitness',
  'Tablets Y Accesorios': 'tecnologia',
  'Tags Para El Pago De Peajes': 'autos-motos',
  'Teclados Y Pianos': 'musica',
  'Telefonía Fija E Inalámbrica': 'tecnologia',
  'Televisores': 'audio-video',
  'Tenis, Pádel Y Squash': 'deportes-fitness',
  'Terapias Alternativas': 'belleza',
  'Testers Y Equipos De Medición': 'herramientas',
  'Textil Y Calzado': 'moda',
  'Textiles De Hogar Y Decoración': 'hogar',
  'Tiro Deportivo': 'deportes-fitness',
  'Tratamientos De Belleza': 'belleza',
  'Tuning': 'autos-motos',
  'Uniformes Y Ropa De Trabajo': 'moda',
  'Varios': 'otros',
  'Vehículos De Juguete': 'bebes-ninos',
  'Vehículos Montables Para Niños': 'bebes-ninos',
  'Voley': 'deportes-fitness',
};

/**
 * Dado el nombre de categoría cruda que viene del breadcrumb de ML,
 * devuelve el slug de la categoría madre correspondiente.
 */
export function getMacroCategorySlug(rawCategoryName?: string): string {
  if (!rawCategoryName) return 'otros';
  return RAW_TO_MACRO[rawCategoryName] || 'otros';
}

export function getMacroCategory(slug: string): MacroCategory | undefined {
  return macroCategories.find((c) => c.slug === slug);
}
